<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTopItemByCategory($categoryId)
    {
        $topByCategory = $this->findOneBy(['category' => $categoryId], ['nbVote' => 'DESC'], 1);

        return $topByCategory;
    }
}
