<?php

namespace AppBundle\Repository;

/**
 * ItemUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemUserRepository extends \Doctrine\ORM\EntityRepository
{
}
