<?php

namespace AppBundle\Repository;

/**
 * UserVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastTenVote()
    {
        return $this->createQueryBuilder('v')
            ->setMaxResults(10)
            ->orderBy('v.createdAt', 'desc')
            ->getQuery()
            ->getResult();
    }
}
